# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master
- feature/*

pool:
  vmImage: 'macOS-10.14'

steps:
- bash: ./setup.sh
  workingDirectory: #
  displayName: Run macsetup.sh
